version: '3.8'
services:
  aiflowy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/aiflowy?useInformationSchema=true&characterEncoding=utf-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - aiflowy-net
    depends_on:
      mysql:
        condition: service_healthy
  aiflowy-ui:
    build:
      context: ./aiflowy-ui-react
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - aiflowy
    networks:
      - aiflowy-net
  mysql:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: aiflowy
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    # 这个命令在默认 entrypoint 运行前修复权限
    entrypoint: sh -c "chown -R mysql:mysql /docker-entrypoint-initdb.d && docker-entrypoint.sh mysqld"
    networks:
      - aiflowy-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
networks:
  aiflowy-net:
