server:
  port: 8080
  address: 0.0.0.0
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.2.6:3306/test?useInformationSchema=true&characterEncoding=utf-8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
aiflowy:
  storage:
    local:
      root: 'D'
  jwt:
    secret: 123123sdfjlakjdfadsafwoieurew
  ollama:
    host: http://127.0.0.1:11434
  login:
    excludes: /api/v1/auth/**
  permission:
    excludes: /api/v1/auth/**
