# 鼓励用户使用 Issue 模板（不允许用户创建空白 Issue）
blank_issues_enabled: false

# 引导用户浏览相关文档
contact_links:
    -   name: AIFlowy 官网
        url: https://aiflowy.tech/
    -   name: AIFlowy 开发文档
        url: https://aiflowy.tech/zh/development/getting-started/getting-started.html
    -   name: AIFlowy 产品手册
        url: https://aiflowy.tech/zh/product/info/what-is-aiflowy.html
    -   name: AIFlowy 版本对比
        url: https://aiflowy.tech/zh/product/pricing.html